spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exchange?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    database: MYSQL

partner.host: http://localhost:8882

spring.liquibase:
  change-log: classpath:database/changelog-develop.yml
  enabled: true

logging.level.com.example.training.trainingkotlin.ExchangeRateAutoClient: DEBUG
feign.client.config:
  default:
    loggerLevel: full

logging.level.feign.Logger: DEBUG
